@baseurl = https://api.annict.com
@token = A5kKRnr5a2_VBFWr2gPMdbh3g0ZIHoB-VfIVbugvTMU
### 春=4,5,6 夏=7,8,9 秋=10,11,12 冬=1,2,3
@season = 2021-spring
@actor = 水瀬いのり
@getNumber = 50

@token = eyJhbGciOiJSUzI1NiIsImtpZCI6ImNhMDA2MjBjNWFhN2JlOGNkMDNhNmYzYzY4NDA2ZTQ1ZTkzYjNjYWIiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhenAiOiIzMjU1NTk0MDU1OS5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsImF1ZCI6IjMyNTU1OTQwNTU5LmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwic3ViIjoiMTEyMTE4NjE3ODQ3MDc3MjE2Nzk5IiwiZW1haWwiOiJrZW5nbzA3MTIyNUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiYXRfaGFzaCI6ImN2Y01EczBpSlVaYXllbkl4TDdVY2ciLCJpYXQiOjE2NDIzODI5MzQsImV4cCI6MTY0MjM4NjUzNH0.tjzDJ5JBN9uKycQtebdQZA_tUii8JpKbn03j2vL1xQwhh7mN9bc8qHqV62kvAkziUN9nWWZaLgOECvPLaz547K1Mt6JDV0ohBUpr8uTNdCp-rTXBndvEil3pTYizVEjO8wLh4T7nQ7RpyREHSozZf5JOSf_nqlie18ijAIsvV2S5E5pUv9eqoZx_OCYLozBint58B3_0jZwVDLwCmlw_cqB_2VsUEXUMBC9YxgOw7_dpfWaISCIZd_Bf2ziq5eUNNtcKBt87-mQAIO4acJcrTWVL9DJQl_HeLMXWFGYoKg1Bs_mWdzYQoPiCfMNSnZ-38oIOVtEPQJ5nVj92-ngJ1A

### シーズンを指定して、作品を検索する
GET {{baseurl}}/v1/works?access_token={{token}}&filter_season={{season}}&per_page={{getNumber}}

### 作品IDを指定して、キャストを検索する
GET {{baseurl}}/v1/casts?access_token={{token}}&filter_work_id=7912

### 作品IDを指定して、スタッフ情報を検索する
GET {{baseurl}}/v1/staffs?access_token={{token}}&filter_work_id=7639

### 作品IDを指定して、スタッフ情報を検索する
GET {{baseurl}}/v1/people?access_token={{token}}&filter_name={{actor}}

### 声優IDを指定して、キャスト情報を検索する
GET {{baseurl}}/v1/casts?access_token={{token}}&filter_ids=7118

### 作品IDを指定して、レビューを検索する
GET {{baseurl}}/v1/reviews?access_token={{token}}&filter_work_id=7227

###
get {{baseurl}}/v1/staffs?access_token=A5kKRnr5a2_VBFWr2gPMdbh3g0ZIHoB-VfIVbugvTMU&filter_work_id=6817

### 本番
GET https://asia-northeast1-oshiani.cloudfunctions.net/getAandGProgramListHttp
Authorization: bearer {{token}}

### 本番 メール通知
GET https://asia-northeast1-oshiani.cloudfunctions.net/notifyRegistedProgramHttp
Authorization: bearer {{token}}


### テスト
GET https://asia-northeast1-oshiani-test.cloudfunctions.net/getAandGProgramListHttp
Authorization: bearer {{token}}


### テスト GA文庫 スクレイピング
GET https://asia-northeast1-oshiani-test.cloudfunctions.net/gaScraiping
Authorization: bearer {{token}}
