@baseurl = https://api.annict.com
@token = A5kKRnr5a2_VBFWr2gPMdbh3g0ZIHoB-VfIVbugvTMU
### 春=4,5,6 夏=7,8,9 秋=10,11,12 冬=1,2,3
@season = 2021-spring
@actor = 水瀬いのり
@getNumber = 50

### シーズンを指定して、作品を検索する
GET {{baseurl}}/v1/works?access_token={{token}}&filter_season={{season}}&per_page={{getNumber}}

### 作品IDを指定して、キャストを検索する
GET {{baseurl}}/v1/casts?access_token={{token}}&filter_work_id=7912

### 作品IDを指定して、スタッフ情報を検索する
GET {{baseurl}}/v1/staffs?access_token={{token}}&filter_work_id=7639

### 作品IDを指定して、スタッフ情報を検索する
GET {{baseurl}}/v1/people?access_token={{token}}&filter_name={{actor}}

### 声優IDを指定して、キャスト情報を検索する
GET {{baseurl}}/v1/casts?access_token={{token}}&filter_ids=7118

### 作品IDを指定して、レビューを検索する
GET {{baseurl}}/v1/reviews?access_token={{token}}&filter_work_id=7227

###
get {{baseurl}}/v1/staffs?access_token=A5kKRnr5a2_VBFWr2gPMdbh3g0ZIHoB-VfIVbugvTMU&filter_work_id=6817

###
GET https://asia-northeast1-oshiani-test.cloudfunctions.net/getAandGProgramListHttp
Authorization: bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Ijc0MjE3YjhkYWRiYjM2NTc4MzU4MGY5ZTkyNDg3ZDcwMWNkMzhmZTYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhenAiOiIzMjU1NTk0MDU1OS5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsImF1ZCI6IjMyNTU1OTQwNTU5LmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwic3ViIjoiMTEyMTE4NjE3ODQ3MDc3MjE2Nzk5IiwiZW1haWwiOiJrZW5nbzA3MTIyNUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiYXRfaGFzaCI6Indka3RwNG01YkdDdTBxZnZ2WXp2aEEiLCJpYXQiOjE2MzE5NTQzNDcsImV4cCI6MTYzMTk1Nzk0N30.bROGfiYhbApuC4mx32UWVs6NxNrMlFVYekoeBq0dj_U6utLuwMVBMCyAC5lL8rE0zv6sR1UHUwYkDAvLxMsebg4rT3Gsp1viJgkRTvte-u27wR7xyr-x4pgiwdj9wl7OSZTUtuNPQa5ltTrVMQBcFjodW6tkA81Wp4qkXAwqY6o42s44M3LHiy4izP_LJopsWEL1e3kM8q5OYM1aF5MEd6ahgnPciroyxbgKrXnyhL4sRv8bD3wc34jl4SW2A5Xnjld3pRtCQWiU1pczZ-BnUvf_2ZHSRmqW0lEoQYwN3Ius5I4Zs7hBzThwhBvEAmooX194vl0-BzIBJYFdSNIbFg