@baseurl = https://api.annict.com
@token = A5kKRnr5a2_VBFWr2gPMdbh3g0ZIHoB-VfIVbugvTMU
### 春=4,5,6 夏=7,8,9 秋=10,11,12 冬=1,2,3
@season = 2021-spring
@actor = 水瀬いのり
@getNumber = 50

### シーズンを指定して、作品を検索する
GET {{baseurl}}/v1/works?access_token={{token}}&filter_season={{season}}&per_page={{getNumber}}

### 作品IDを指定して、キャストを検索する
GET {{baseurl}}/v1/casts?access_token={{token}}&filter_work_id=7912

### 作品IDを指定して、スタッフ情報を検索する
GET {{baseurl}}/v1/staffs?access_token={{token}}&filter_work_id=7639

### 作品IDを指定して、スタッフ情報を検索する
GET {{baseurl}}/v1/people?access_token={{token}}&filter_name={{actor}}

### 声優IDを指定して、キャスト情報を検索する
GET {{baseurl}}/v1/casts?access_token={{token}}&filter_ids=7118

### 作品IDを指定して、レビューを検索する
GET {{baseurl}}/v1/reviews?access_token={{token}}&filter_work_id=7227

###
get {{baseurl}}/v1/staffs?access_token=A5kKRnr5a2_VBFWr2gPMdbh3g0ZIHoB-VfIVbugvTMU&filter_work_id=6817

### 本番
GET https://asia-northeast1-oshiani.cloudfunctions.net/getAandGProgramListHttp
Authorization: bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjhkOTI5YzYzZmYxMDgyYmJiOGM5OWY5OTRmYTNmZjRhZGFkYTJkMTEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhenAiOiIzMjU1NTk0MDU1OS5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsImF1ZCI6IjMyNTU1OTQwNTU5LmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwic3ViIjoiMTEyMTE4NjE3ODQ3MDc3MjE2Nzk5IiwiZW1haWwiOiJrZW5nbzA3MTIyNUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiYXRfaGFzaCI6IjA3ZFJWbWh5Y1V3bjFLLVhkRlRaOVEiLCJpYXQiOjE2MzI4ODUyMjYsImV4cCI6MTYzMjg4ODgyNn0.11zi89iEzqJuMvm2wvrhFIFotWt5-nGQ1aasSSaSMi2vapAWdTe7gVDBlqQ23F8C0pVQjZOgu8hFV_adb0M_YjxrOZXlEIRJTk-RzpIL2rnUR1pjnyM8erBYjAS3n1H4gs0AYRIwbvARR2CdHmgtlkja5i6NPY2ODpRS2JxXhEhBYSDo-0T14cMQXH_e14Vwnv8_Afudqzbyfz-HugMQ10tuiR89BM2NxZs40JMywO1spUZ_1TDAFU9QSdd4iPblEe0HaO3Y47MknkI30NnfuDAy-QbU6AmhN9lCARA4lFvweg07aB3HIqY-xor3-kYNJl0G_eSF9czRRot2j78i2Q
### テスト
GET https://asia-northeast1-oshiani-test.cloudfunctions.net/getAandGProgramListHttp
Authorization: bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjhkOTI5YzYzZmYxMDgyYmJiOGM5OWY5OTRmYTNmZjRhZGFkYTJkMTEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhenAiOiIzMjU1NTk0MDU1OS5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsImF1ZCI6IjMyNTU1OTQwNTU5LmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwic3ViIjoiMTEyMTE4NjE3ODQ3MDc3MjE2Nzk5IiwiZW1haWwiOiJrZW5nbzA3MTIyNUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiYXRfaGFzaCI6IkdJWnIxcnkxSUJJNHotQXdOc2JWYUEiLCJpYXQiOjE2MzMzMTgxNzUsImV4cCI6MTYzMzMyMTc3NX0.z9bUZwXMFifyFtwuxR4DA3FImlqIv5N6aqN6ZzMeXF1L5S_cWnhnYn82uw0YvzjGROEB1-lEfilfK4SOqeuKXvsxyRgDjD4DLKeiW2htHj5BI0kHR50A9m7Co9P_ONidFXwFBhe1GiJQCLEyvq_r59SuuBTMWhss0wD4OkB7WTrl7P_qgVEHhJFAXTffOkm4p1YD1gg1AuIBV8ayZ_gpO6puiNt6_kgUJPgmSm18BDzwG28qg-jVdr7eloQ9vXflf7M4jbA3WTnHFeUFDa9VQP8QRJkO1xVGkgFSbSepg9ycvq9dJzI8ezkNXMi7gaJT7LAzxcibL1sFr9o9xSQ_Ng